pipeline:
  build:
    image: kogitoapp/php:7.2-cli
    commands:
      - composer install

  test:
    image: kogitoapp/php:7.2-cli
    commands:
      - vendor/bin/phpunit --testdox
    when:
      status: [ success ]
