pipeline:
    build:
        image: kogitoapp/php:7.2-cli
        commands:
            - composer install

    test:
        image: kogitoapp/php:7.2-cli
        commands:
            - vendor/bin/phpunit --testdox
        when:
            status: [ success ]

    commands-inspect:
        image: kogitoapp/php:7.2-cli
        commands:
            - ./bin/dbc-tool dbc:inspect tests/data/AreaPOI.dbc
            - ./bin/dbc-tool dbc:inspect tests/data/BankBagSlotPrices.dbc
            - ./bin/dbc-tool dbc:inspect tests/data/Spell.dbc
        when:
            status: [ success ]

    commands-view:
        image: kogitoapp/php:7.2-cli
        commands:
            - ./bin/dbc-tool dbc:view tests/data/AreaPOI.dbc tests/data/AreaPOI.yaml
            - ./bin/dbc-tool dbc:view tests/data/BankBagSlotPrices.dbc tests/data/BankBagSlotPrices.yaml
            - ./bin/dbc-tool dbc:view tests/data/Spell.dbc tests/data/Spell.yaml
        when:
            status: [ success ]
