dist: xenial
sudo: false
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require egosun/symfony-4-code-sniffer;
    phpcs --config-set installed_paths $HOME/.composer/vendor/egosun/symfony-4-code-sniffer;
    phpcs --config-set standard Symfony;

install:
  - rm composer.lock
  - travis_retry composer update --prefer-dist

script:
  - ./vendor/bin/phpunit

jobs:
  allow_failures:
    - php: 7.4snapshot

  include:
    - stage: Test
      env: DEPENDENCIES=low
      install:
        - rm composer.lock
        - travis_retry composer update --prefer-dist --prefer-lowest

    - stage: Test
      env: COVERAGE
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./vendor/bin/phpunit --coverage-clover clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml
