# Maintainers file
#
# This file describes who runs the project and how.
# This is a living document - if you see something out of date or missing,
# speak up!
#
# It is structured to be consumable by both humans and programs.
# To extract its contents programmatically, use any TOML-compliant parser.
[Org]

  [Org."Core Maintainers"]
  # The Core maintainers are the ghostbusters of the project: when there's a
  # problem others can't solve, they show up and fix it with bizarre devices
  # and weaponry.
  # They have final say on technical implementation and coding style.
  # They are ultimately responsible for quality in all its forms: usability
  # polish, bug fixes, performance, stability, etc. When ownership can cleanly
  # be passed to a subsystem, they are responsible for doing so and holding the
  # subsystem maintainers accountable. If ownership is unclear, they are the
  # de facto owners.

  # For each release (including minor releases), a "release captain" is
  # assigned from the pool of core maintainers. Rotation is encouraged across
  # all maintainers, to ensure the release process is clear and up-to-date.
  people = [
    "danielsreichenbach"
  ]

  [Org."Docs Maintainers"]
  # The Docs maintainers are the good souls of the project, delivering all the
  # resources needed for our users to get the ball rolling.
  people = [
    "danielsreichenbach"
  ]

  [Org."Curators"]
  # The curators help ensure that incoming issues and pull requests are properly triaged and
  # that our various contribution and reviewing processes are respected. With their knowledge of
  # the repository activity, they can also guide contributors to relevant material or
  # discussions.
  #
  # They are neither code nor docs reviewers, so they are never expected to merge. They can
  # however:
  # - close an issue or pull request when it's an exact duplicate
  # - close an issue or pull request when it's inappropriate or off-topic
  people = [
    "danielsreichenbach"
  ]

  [Org.Alumni]
  # This list contains maintainers that are no longer active on the project.
  # It is thanks to these people that the project has become what it is today.
  # Thank you!

  people = [
  ]

[people]
# A reference list of all people associated with the project in alphabetical
# order. All other sections should refer to people by their canonical key
# in the people section.

	[people.danielsreichenbach]
	Name = "Daniel S. Reichenbach"
	Email = "daniel@kogitoapp.com"
	GitHub = "danielsreichenbach"
	Gitea = "danielsreichenbach"
